### ISSUE TITLE
Zoom setting not working

### ISSUE THREAD

**Issue by dbd5** [yii2mod/yii2-google-maps-markers#14]
Hello,

It appears that the zoom setting is not working, my map stays the same size no matter what setting I put  in zoom.
...
    'googleMapsOptions' => [
        'mapTypeId' => 'roadmap',
        'tilt' => 45,
        **'zoom' => 5,**
    ],

Thanks for your support

Adam

**Comment by ihorchepurnyi** [comment]
Hi, @dbd5 
`zoom` property only works when the map is empty. When you use the `userLocations`, our js script automatically sets `zoom` and `center` properties for the map.
