### ISSUE TITLE
Language change not working

### ISSUE THREAD

**Issue by jiimka** [yii2mod/yii2-google-maps-markers#16]
\yii2mod\google\maps\markers\GoogleMaps::getGoogleMapsUrlOptions method has 'en' language set as default value, which overrides any custom language setting from the params.
```
return ArrayHelper::merge($this->googleMapsUrlOptions, array_filter([
            'v' => '3.exp',
            'key' => null,
            'libraries' => null,
            'language' => 'en',
        ]));
```

**Comment by jiimka** [comment]
Sorry, it is already fixed here:
https://github.com/yii2mod/yii2-google-maps-markers/pull/11
Just need to switch to the dev-master version in composer.
Closing the issue.

**Comment by ihorchepurnyi** [comment]
I have created a new release, please update your package.
