### ISSUE TITLE
How to use 'resize' event correctly ?

### ISSUE THREAD

**Issue by nagaokashi** [yii2mod/yii2-google-maps-markers#2]
I used 2 below commands, but they did not work.
1. google.maps.event.trigger(yii.googleMapManager.map, 'resize');
2. google.maps.event.trigger(map, 'resize');

My problem is posted here:
http://stackoverflow.com/questions/37370433/googlemaps-does-not-show-on-inactive-tab-yii2/37373251#37373251

**Comment by ihorchepurnyi** [comment]
Hi, try this (http://jsfiddle.net/lokeshpahal/2MNnH/2/)

**Comment by nagaokashi** [comment]
Thanks Igor. Sorry I could not catch up your solution. You mean that I have to use all code of this example  (http://jsfiddle.net/lokeshpahal/2MNnH/2/)? Or just a piece of them.

**Comment by ihorchepurnyi** [comment]
I think you can try to resize the main container of the google map. In this example http://jsfiddle.net/lokeshpahal/2MNnH/2/ to resize the google map they just resize the height of the main container of the map `#map-canvas` without using the google map api. Try to resize the main `div` container in your event and reinit the google map.

**Comment by nagaokashi** [comment]
Thanks Igor. I tried adding this code `<?= \yii\helpers\Html::button('Resize', ['onclick' => 'document.getElementById("map_canvas").style.height = "50%";' ]) ?>`
After click the button, the map size has changed but the map content was not changed.

**Comment by ihorchepurnyi** [comment]
Ok, thanks. Now I gonna try to resolve this problem and I'll answer you later.

**Comment by nagaokashi** [comment]
Thank you very much Igor.
I got the solution.
`<?= \yii\helpers\Html::button('Resize', ['onclick' => 'google.maps.event.trigger(yii.googleMapManager.map, "resize");' ]) ?>`

Exactly, I did as below for my original issue.

```
echo TabsX::widget([
        'items'=>$datsan_tab_items,
        'position'=>TabsX::POS_ABOVE,
        'bordered'=>false,
        'encodeLabels'=>false,
        'pluginEvents' => [
            "tabsX.click" => "function() {
                 setTimeout(function() {
                     google.maps.event.trigger(yii.googleMapManager.map, 'resize');
                 }, 1000);
           }"
        ]
    ]);
```

P/S: Thanks Matej P for this solution.

**Comment by ihorchepurnyi** [comment]
It's very nice. Thanks
