### ISSUE TITLE
How to show current location ? 

### ISSUE THREAD

**Issue by nagaokashi** [yii2mod/yii2-google-maps-markers#5]
How to show current location by a marker or a blue point (same navi) ?
` <?php
        echo GoogleMaps::widget([

            'userLocations' => $locat,

            'googleMapsUrlOptions' => [

                'key' => Yii::$app->params['GOOGLE_API_KEY'],

            ],

            'googleMapsOptions' => [
//                'center' => [38.50, -90.50],

            ],

            'wrapperHeight' => '350px',

      ]);
    ?>`

**Comment by ihorchepurnyi** [comment]
You only can set locations via array, as following

``` php
      'userLocations' => [
            [
                'location' => [
                    'address' => 'Kharkov',
                    'country' => 'Ukraine',
                ],
                'htmlContent' => '<h1>Kharkov</h1>'
            ],
            [
                'location' => [
                    'city' => 'New York',
                    'country' => 'Usa',
                ],
                'htmlContent' => '<h1>New York</h1>'
            ],
      ]
```
