### ISSUE TITLE
How to setcenter by latitude and longitude that are get from javarsript  ? 

### ISSUE THREAD

**Issue by nagaokashi** [yii2mod/yii2-google-maps-markers#6]
My code is as below.
`<?php
        echo GoogleMaps::widget([

            'userLocations' => $locat,

            'googleMapsUrlOptions' => [

                'key' => Yii::$app->params['GOOGLE_API_KEY'],

            ],

            'googleMapsOptions' => [

//                'center' => [38.50, -90.50],

            ],

            'wrapperHeight' => '350px',

      ]);

    ?>`

This is my js function:
`function show_map_theo_address(address) {
            var geocoder, vitri;
            var minZoomLevel = 15;
            geocoder = new google.maps.Geocoder();
            if (geocoder) {
                geocoder.geocode({
                    'address': address
                }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
                            vitri = results[0].geometry.location;
                            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                                zoom: minZoomLevel,
                                center: new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng()),
                                mapTypeId: google.maps.MapTypeId.ROADMAP
                            });
                            }
                        }
                    }
                });
            }

        }`

But it does not work.

**Comment by nagaokashi** [comment]
I mean that I want to change the center value to a expected position.

**Comment by ihorchepurnyi** [comment]
Hi, this plugin does not search by latitude/longitude, only by [address string](https://github.com/yii2mod/yii2-google-maps-markers/blob/master/assets/googlemap.js#L38).

**Comment by morontt** [comment]
@nagaokashi Use **center** option

``` php
<?php echo GoogleMaps::widget([
    'userLocations' => [
        // ....
    ],
    'googleMapsUrlOptions' => [
        'key' => Yii::$app->params['GOOGLE_API_KEY'],
    ],
    'googleMapsOptions' => [
        // ...
        'center' => ['lat' => 38.50, 'lng' => -90.50],
    ],
]); ?>
```
